#' Generate Detection History Matrix for Occupancy Modeling
#'
#' Summarizes BirdNET detection data across specified survey intervals (occasions)
#' and aligns them with operational effort data to create a site-by-occasion matrix.
#'
#' @param detection_data A data frame containing BirdNET detections, including
#'   `filepath` and `confidence` columns.
#' @param effort_data A data frame generated by [birdnet_get_effort()] containing
#'   `site`, `date`, and `n_files`.
#' @param survey_interval A character string specifying the temporal unit for
#'   grouping survey occasions (e.g., `"1 day"`, `"1 week"`, `"7 days"`). Passed
#'   directly to [lubridate::floor_date()].
#' @param i An integer specifying the path index for site extraction. Passed
#'   directly to [birdnet_add_site()]. Defaults to `-2`.
#'
#' @return A wide tibble (matrix format) where rows represent unique sites,
#'   columns represent sequential temporal occasions, and cell values indicate
#'   the total number of detections. Gaps in operational effort are preserved as `NA`.
#'
#' @export
birdnet_detection_history <- function(detection_data, effort_data, survey_interval, i = -2) {

  # 1. Summarize detections by site and occasion block
  detections_summarized <- detection_data |>
    birdnet_add_site(i = i) |>
    birdnet_add_datetime() |>
    dplyr::mutate(occasion = lcl_date <- lubridate::floor_date(date, unit = survey_interval)) |>
    dplyr::group_by(site, occasion) |>
    dplyr::summarise(
      n_detections = dplyr::n(),
      max_conf = max(confidence, na.rm = TRUE),
      max_conf_audio = filepath[which.max(confidence)],
      .groups = "drop"
    )

  # 2. Process effort, join detections, fill zeros, and pivot wide
  detection_matrix <- effort_data |>
    dplyr::mutate(occasion = lcl_date <- lubridate::floor_date(date, unit = survey_interval)) |>
    dplyr::group_by(site, occasion) |>
    dplyr::summarise(n_files = sum(n_files, na.rm = TRUE), .groups = "drop") |>

    # Left join ensures we only evaluate occasions where the devices were running
    dplyr::left_join(detections_summarized, by = c("site", "occasion")) |>

    # Differentiate true zeros from missing effort
    dplyr::mutate(
      n_detections = tidyr::replace_na(n_detections, 0),
      max_conf = tidyr::replace_na(max_conf, 0),
      max_conf_audio = tidyr::replace_na(max_conf_audio, "none")
    ) |>

    # Isolate matrix structure and shape wide for modeling packages (e.g., unmarked)
    dplyr::select(site, occasion, n_detections) |>
    tidyr::pivot_wider(
      names_from = occasion,
      values_from = n_detections,
      values_fill = NA
    )

  return(detection_matrix)
}
